# -*- coding: utf-8 -*-
"""Python African Problem Solver.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AGegzwPI6m4socF_JQCxbHp9VxsGis1T
"""

#Exchange Rate Program (April 2026)
naira = 1
dollar = 0.00074
cedi = 1
rand = 1.50
swissfranc = 1
canadiandollar = 1.75

print(dollar * (naira * 10000))
print(rand * (cedi*10000))
print(swissfranc * (canadiandollar * 10000))

#GDP Categorizer
Nigeria = 285000000000
USA = 30620000000000
Switzerland = 936600000000

if Nigeria < 30000000:
    print("LOW")

elif Nigeria < 100000000000:
    print("MIDDLE")

else:
    print("HIGH")

if USA < 3000000000:
  print("LOW")

elif USA < 100000000000:
  print("MIDDLE")

else:
  print("HIGH")

if Switzerland < 3000000000:
  print("LOW")

elif Switzerland < 10000000000000:
  print("MIDDLE")

else:
  print("HIGH")

#Top 3 Cities by Population

population = [23000000, 17804000, 5325000, 2000000 ]

population.sort(reverse=True)
print(population[:3])

#Country to Capital Lookup
capitals = {'Nigeria': 'Abuja', 'Kenya': 'Nairobi', 'Egypt': 'Cairo',
    'Ethiopia': 'Addis Ababa', 'Ghana': 'Accra', 'South Africa': 'Pretoria',
    'Morocco': 'Rabat', 'Uganda': 'Kampala', 'Rwanda': 'Kigali', 'Senegal': 'Dakar'}

user_choice = input("Enter a country: ")
print(capitals.get(user_choice))

#Student Score Analyzer

def analyze_scores(score_list):
    avg = sum(score_list) / len(score_list)
    high = max(score_list)
    low = min(score_list)
    return avg, high, low  # This is returning a "Tuple"

# Tuple Unpacking: 3 variables catch 3 answers
scores = [85, 90, 50, 65, 40]
average, highest, lowest = analyze_scores(scores)

print(f"Average: {average}, Max: {highest}, Min: {lowest}")

